---
name: Manage labels

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v5.2.0
        with:
          skip-delete: true
